CREATE TABLE `Events` (
	`id` CHAR(36) NOT NULL PRIMARY KEY,
	`version` BIGINT UNSIGNED NOT NULL,
	`startTime` DATETIME NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`subtitle` VARCHAR(255) NOT NULL,
	`series` VARCHAR(255) NOT NULL,
	`text` MEDIUMTEXT NOT NULL,
	`lineup` MEDIUMTEXT NOT NULL,
	`price` VARCHAR(255) NOT NULL,
	`entry` TIME NULL,
	`notes` MEDIUMTEXT NOT NULL,
	`image` MEDIUMTEXT NULL,
	`links` MEDIUMTEXT NOT NULL
)  ENGINE=INNODB;