on:
  push:
    branches:
      - web

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: admin.lepirate-rosenheim.de
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sudo apt install rclone -y
          rclone config create remote sftp host "web14.ronet.de" user "F16131442495" port "2222" pass "${{ secrets.RCLONE_OBSCURED_PASSWORD }}"
          rclone sync -v html remote:test