on:
  push:
    branches:
      - web

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: admin.lepirate-rosenheim.de
    steps:
      - name: Install Packages
        run: |
          sudo apt install rclone git-restore-mtime -y
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Reset Modification Time
        run: |
          git restore-mtime
      - name: Configure RClone
        run: |
          rclone config create remote sftp host "web14.ronet.de" user "F16131442495" port "2222" pass "${{ secrets.RCLONE_OBSCURED_PASSWORD }}"
      - name: Sync
        run: |
          rclone sync -v html remote:html